M2: Maven
EvgeniyMakuta/QaseDiplomaTMS pull request #2
Opened 2021-03-04 18:54 UTC by EvgeniyMakuta

2021-03-10 20:38 UTC, vchesnakoutest requested changes
please make fixes

2021-03-10 20:38 UTC, vchesnakoutest commented on src/main/java/builders/ProjectBuilder.java
> +        return project;
можно сделать сразу:
        return Project.builder()
                .title(getProjectName())
                .code(getCode())
                .description(PROJECT_DESCRIPTION)
                .accessType(PUBLIC)
                .build();

2021-03-10 20:38 UTC, vchesnakoutest commented on src/main/java/builders/ProjectBuilder.java
> +        return project;
тоже самое

2021-03-10 20:38 UTC, vchesnakoutest commented on src/main/java/builders/TestCaseBuilder.java
> +        return testCase;
тоже можно сразу return делать

2021-03-10 20:38 UTC, vchesnakoutest commented on src/main/java/pages/SettingsPage.java
> +    WebElement alertMegLocator;
alertMessageLocator ?

2021-03-10 20:38 UTC, vchesnakoutest commented on src/test/java/tests/ProjectTest.java
> +        assertEquals(statusCode, 200, "Status code should be 200 instead of " + statusCode);
давай не мешать API и UI тесты в одном классе.

лучше даже в разные пакеты их положить, например ui_tests, api_tests

2021-03-11 19:40 UTC, EvgeniyMakuta commented on src/main/java/builders/ProjectBuilder.java
> +        return project;
use log.debug(String.format("Getting project %s", project.toString())); 
so I need 'project' for that

2021-03-11 23:20 UTC, merged