M3: Added Logging / RetryAnalyzer / Allure /  TestNG annotations + pa…
EvgeniyMakuta/QaseDiplomaTMS pull request #3
Opened 2021-03-12 01:12 UTC by EvgeniyMakuta

…rallel /

2021-03-12 07:27 UTC, vchesnakoutest requested changes
please make fixes

2021-03-12 07:27 UTC, vchesnakoutest commented on src/main/java/adapters/BaseAdapter.java
> +        String apiTokenValue = System.getenv().getOrDefault("apiToken", PropertyReader.getProperty("apiToken"));
"apiToken" - как вариант можно тоже в константу, смотри сам

2021-03-12 07:27 UTC, vchesnakoutest commented on src/main/java/builders/ProjectBuilder.java
>                  .description(PROJECT_DESCRIPTION)
ещё момент: в классах ProjectBuilder, TestCaseBuilder, UserBuilder можно создать приватные конструкторы этих классов, чтобы ограничить создание объектов этих классов, т.к. все методы внутри статические. Тут опять же решай сам, я бы советовал так сделать.

2021-03-12 07:27 UTC, vchesnakoutest commented on src/main/java/pages/CreateProjectPage.java
> +        new Radio(PROJECT_ACCESS_TYPE_LOCATOR, PROJECT_ACCESS_TYPE_RADIO_LABEL, driver).select(project.getAccessType().getField()); //log.info(String.format("Creating project with following fields: P
log.info закоменчено почему-то

2021-03-12 07:27 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +        log.debug(String.format("Login with email: %s. password: %s", email, password));
password - можно с большой буквы, будет красивее )

2021-03-12 07:27 UTC, vchesnakoutest commented on src/main/java/steps/CreateTestCaseStep.java
> +    }
я бы лучше объеденил эти два степа в один и назвал просто createNewTestCase.

Внутри createFirstTestCase (название поменял бы на createNewTestCase) можно сделать логику:
если отображается кнопка NEW - делаем clickOnCreateNewCase();
если отображается кнопка PLUS - делаем clickOnPlusCase();

в данном случае мы не будем зависеть от того, какой BDD степ нам надо поставить первым, какой вторым и тд

2021-03-12 07:27 UTC, vchesnakoutest commented on src/main/java/steps/ProjectStep.java
> +    }
не уверен, что он тут нужен в степах. В тестах по сути можно и из пейджи его вызвать.

2021-03-12 07:27 UTC, vchesnakoutest commented on src/main/java/steps/ProjectStep.java
> +    }
одинарные методы в степах обычно не делают. степы нужны именно для того, чтобы сделать последовательную логику из нескольких методов

2021-03-12 07:27 UTC, vchesnakoutest commented on src/main/java/steps/ProjectsStep.java
> +    }
тоже самое

2021-03-12 07:27 UTC, vchesnakoutest commented on src/main/java/steps/SettingsStep.java
> +    }
тоже

2021-03-12 07:27 UTC, vchesnakoutest commented on src/test/java/tests/ProjectTest.java
> +                .createProject(project);
на подумать: по сути в степе createProject можно сделать и login. Пока можно оставить так, если останется время можно улучшить

2021-03-12 07:27 UTC, vchesnakoutest commented on src/test/java/utils/AllureUtils.java
> +public class AllureUtils {
screenshot это часть Selenium. Лучше класс назвать просто SсreenshotUtils например

2021-03-12 07:27 UTC, vchesnakoutest commented on src/test/java/utils/TestListener.java
> +                return ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
можно воспользоваться методом из AllureUtils.takeScreenshot

2021-03-12 07:27 UTC, vchesnakoutest commented on src/test/resources/allure.properties
> +allure.link.tms.pattern=https://instagram.com/{}
эти точно тут нужны ?

2021-03-12 09:35 UTC, EvgeniyMakuta commented on src/main/java/adapters/BaseAdapter.java
> +        String apiTokenValue = System.getenv().getOrDefault("apiToken", PropertyReader.getProperty("apiToken"));
writing 'not allowed here'. Do u now why that?
private static final String apiTokenValue = System.getenv().getOrDefault("apiToken", PropertyReader.getProperty("apiToken"));

2021-03-12 09:40 UTC, EvgeniyMakuta commented on src/test/resources/allure.properties
> +allure.link.tms.pattern=https://instagram.com/{}
removed

2021-03-12 09:47 UTC, EvgeniyMakuta commented on src/test/java/utils/TestListener.java
> +                return ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
done

2021-03-12 09:48 UTC, EvgeniyMakuta commented on src/test/java/tests/ProjectTest.java
> +                .createProject(project);
good point. Will think later

2021-03-12 10:10 UTC, EvgeniyMakuta commented on src/main/java/steps/CreateTestCaseStep.java
> +    }
done

2021-03-12 10:20 UTC, EvgeniyMakuta commented on src/main/java/pages/CreateProjectPage.java
> +        new Radio(PROJECT_ACCESS_TYPE_LOCATOR, PROJECT_ACCESS_TYPE_RADIO_LABEL, driver).select(project.getAccessType().getField()); //log.info(String.format("Creating project with following fields: P
removed

2021-03-12 17:44 UTC, EvgeniyMakuta commented on src/main/java/adapters/BaseAdapter.java
> +        String apiTokenValue = System.getenv().getOrDefault("apiToken", PropertyReader.getProperty("apiToken"));
done

2021-03-13 20:34 UTC, vchesnakoutest approved these changes

2021-03-13 20:36 UTC, merged